### ISSUE TITLE
Latest Steam update has broken this :(

### ISSUE THREAD

**Issue by mv0hra** [mpm11011/ac7-ultrawide#18]
First of all thank you for your hard work. In reality the game should natively support most resolutions.

The latest update on Steam has resulted most menu sizes to be 10 x 6cm and illegible. And the actual game play is only on 1 screen now.
Also the cockpit HUD has disappeared - possibly showing on one of the other screens.

Please help!

**Comment by 1992Andrew** [comment]
Sigh, way to go Bandi Namco. Yeah, the latest patch has completely broken this fix for ultrawidescreen; even after I verify the game files and properly reapply this fix everything is still broken. Its looking like its properly resizing menus for my 3440 by 1440 resolution but somehow the game is still being restricted to non-ultrawide resolution and so the menus end up just shrunken and black bars on the left and right of the screen. Its like you took what it looks like normally with no ultrawide fix and just shrunk down everything you see but while still having the HUD offset to the right. I'm guessing that maybe their latest "patch" shifted the location of the HEX values that this fix is supposed to modify in order to allow for ultrawide? And so now the fix is accidentally modifying the wrong HEX values, but I'm no good with code, just guessing here.

Really hoping mpm11011 sees this soon and can fix it (again). Was looking forward to trying some of the new aircraft skins....

**Comment by EPuigdemont** [comment]
Confirming this issue as well.

**Comment by WinkelCode** [comment]
The ultrawide fix has been updated with a fix for the new version.

**Comment by massimilianodelliubaldini** [comment]
Thanks to @martinsstuff for figuring out where the letterboxing bytes went!

@1992Andrew you're absolutely correct in your analysis. But I will defend Namco by saying that they probably had no idea about this happening, nor had they any control to prevent it. It's not like the engineers were writing all these updates in bytecode. They probably changed nothing about the FOV, letterboxing, etc. directly, but their compiler probably rearranged this information differently than it ever had before.

I do wish they would prioritize ultrawide support at some point, but it's not like I'm ever going to say no to new planes or skins. :)

**Comment by teaswift** [comment]
Updated fix is working for me as of 1/22/21. I did however have to switch from borderless to fullscreen. Thank you!

**Comment by 1992Andrew** [comment]
@mpm11011 Awesome work man, thank you! Oh and I'm just given Namco a hard time, they made a great game and I love it. I'm sure they didnt do it on purpose nor were even thinking about it; I just find it funny that their update which ostensibly wouldn't have had anything to with the resolution or FOV, nonetheless by chance happened to push just the right thing such that it would break your ultrawide fix. 

Thanks again as always, and good on martinsstuff too!
