### ISSUE TITLE
Top Gun DLC broke it?

### ISSUE THREAD

**Issue by WhoIsMoloBartell** [mpm11011/ac7-ultrawide#26]
I think the Top Gun Maverick DLC has broken this solution. Will there be an update?

**Comment by DAOWAce** [comment]
Sure did.. just got the game after watching the new movie and can't play it, woohoo.

Last talk about this stuff was back in March, before the release of the movie/dlc update: https://github.com/mpm11011/ac7-ultrawide/issues/22

Shelved yet another game..

**Comment by WinkelCode** [comment]
Hey everyone, I will take a look at it when I get the time. Unfortunately I have some other stuff to work on at the moment, but I will try to get around to it.

Edit: My username used to be "martinsstuff", I did some work on the fix alongside @mpm11011

**Comment by WinkelCode** [comment]
@WhoIsMoloBartell @DAOWAce Could you please specify what is broken, it seems to work fine on my end.

(As I said in the other thread, you need to use [Steamless](https://github.com/atom0s/Steamless) before patching. Make sure to rename `Ace7Game.exe.unpacked.exe` to `Ace7Game.exe` so the script finds it.

Edit: Also tagging @Batate1 (they reacted to my reply)

**Comment by DAOWAce** [comment]
Uh.. well that's weird.  Was there a game update since posting that changed something?

The patcher used to error out even on the Steamless .exe, now it patches fine.

Though, the UI still goes nuts ingame, constantly changing between some scenes, and it's letterboxed in the main menus.  Here's a demo recording _(which I've now discovered is extremely choppy)_:

Stock: https://www.youtube.com/watch?v=5RuhjJ3STKQ
Ultrawide: https://www.youtube.com/watch?v=DPzGzK0DvIg

Unless this is a known issue (which it would be useful to list!).  Just seemed broken.

**Comment by WinkelCode** [comment]
@DAOWAce I see a couple things in your video

* Splash screen and main menu are zoomed out, this is due to the FOV modification, as they seem to be sort of(?) present in 3D space. You can see how parts of the menu can be seen in the "off-screen" area.
* Zoom in/out in the hangar while changing aircraft. Note how this happens only while it is loading, not sure what part of the fix causes that.
* Fade in screen being offset, this is due to having to shift the HUD, which also affects the black texture that fades out.
* In the rocket camera, the subtitles are shifted to the left, we are using a suboptimal way of determining if we're in-game since we can't apply the HUD-shifting system at all times as this would cause other issues. The rocket camera happens to be a place where this fails.
* Also, the loading screen looks slightly different due to text and image alignment stuff.

If there are any issues I missed, let me know and I can say if they're known or unexpected behavior.

I played through the entire AC7 story + DLC with the fix and it was never too immersion breaking for me. While actually playing, the distractions should be minimal (just the fade in and occasional shifted subtitles). The menus are just a bit of a weak point for the fix.

**Comment by WhoIsMoloBartell** [comment]
> @WhoIsMoloBartell @DAOWAce Could you please specify what is broken, it seems to work fine on my end.
> 
> (As I said in the other thread, you need to use [Steamless](https://github.com/atom0s/Steamless) before patching. Make sure to rename `Ace7Game.exe.unpacked.exe` to `Ace7Game.exe` so the script finds it.
> 
> Edit: Also tagging @Batate1 (they reacted to my reply)

Hi there,

Sorry for the delay in replying, I was away from my PC for a few weeks.

A bit of background: this is the first time I have played the game and tried the 32:9 patch. For whatever reason at the time it wasn't working for me, but is fine now - and the only explanation I found (reddit) was that the Top Gun DLC broke it. I can confirm that the process works for current version.

However my issue now is that the HUD is off centre (attachment)

No idea if this is something i'm missing or a genuine issue, but I can't find any info on this.

![AceCombat7329 (Large)](https://user-images.githubusercontent.com/103775859/210227316-ccfb7d52-8c06-4431-b9f1-4b2cf1573de5.png)

**Comment by WinkelCode** [comment]
@WhoIsMoloBartell I see you closed the issue, is the off-center HUD fixed for you?

Off center HUD means 3Dmigoto wasn't applied properly, try deleting everything from the game folder except the "Engine" and "Game" folders, verifying game files in Steam and then reinstalling the fix. Make sure you have the unextracted "3Dmigoto-1.3.16.zip" file in the game folder, as per the instructions.

**Comment by WhoIsMoloBartell** [comment]
Your suggestion of deleting everyone worked - OK to be closed now.

Thanks a million for your tool - and help.

**Comment by WinkelCode** [comment]
> Your suggestion of deleting everyone worked - OK to be closed now.
> 
> Thanks a million for your tool - and help.

Glad to hear it works now. For the record: Here's who is responsible for what:
* Widescreen Gaming Forum (that was pre-reddit move) user `susahamat` came up with the FOV change and black bar removal
* I, with guidance from [DarkStarSword](https://github.com/DarkStarSword), came up with the initial HUD fix. I also did the very first black bar removal with hex edits from another Bandai Namco UE4 game (Tekken I think?), can't remember what the differences between the two are exactly (they look a bit different in some cases), but we're preferring `susahamat`'s version.
* [mpm11011](https://github.com/mpm11011) made the Python script and reworked parts of the HUD fix to work generically via Regex expressions.
