### ISSUE TITLE
Suggestion: Add warning about possible anti-cheat issues in the coming soon MP anti-cheat update

### ISSUE THREAD

**Issue by martinsstuff** [mpm11011/ac7-ultrawide#4]
My suggested text:

>Warning: This modification may be detected as a cheating tool and/or considered an "unfair advantage" (due to the increased field of view) by the new Ace Combat 7 anti-cheating measure going live at the end of August.

>The developers have stated that anti-cheat measures won't affect single player mods so we highly recommend not playing online with it installed until we have more information.

>You can find more details at: https://service-en.bandainamcoent.eu/app/detail/a_id/4820/m/ACE%20COMBAT%207:%20SKIES%20UNKNOWN/t/Anti-Cheat%20FAQ/p/7312

**Comment by mpm11011** [comment]
I've opened a ticket with Namco to see if they know whether or not the anticheat system will flag this mod. 

In the meantime, I will add this warning to the script and have the user indicate their acceptance before continuing. I may also write a "disable" script to remove the mod so that people can still play online with relative ease.

When the anticheat launches, if Namco hasn't responded, then I'll try to play online myself with the mod in place and see what happens. Nothing ventured, nothing gained. :)

**Comment by mpm11011** [comment]
a84f381ea32c2eafbc1812190fd4b8f47206f91d

Warning added. Leaving this issue open so I can investigate the anticheat when it goes live.

**Comment by martinsstuff** [comment]
![image](https://user-images.githubusercontent.com/29005772/64476821-aca46a80-d161-11e9-9917-05bb4fff1bc1.png)

Seems like it's ok to use!

**Comment by mpm11011** [comment]
Sweet! Thank you!
